pipeline {
    agent any
    environment {
        SCANNER_HOME = tool 'sonarqube-scanner'
    }
    stages{
        stage (git){
            steps{
                git branch: 'main', url: 'https://github.com/LIKITH-coder/live01'
            }
        }
        stage(maven){
            steps{
                sh 'mvn clean package'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv('sonarqube') {
                        // Run the SonarQube Scanner
                        sh "${env.SCANNER_HOME}/bin/sonar-scanner -Dsonar.projectKey=pipeline -Dsonar.projectName=pipeline -Dsonar.projectVersion=1.0 -Dsonar.sources=src/main/webapp/."
                    }
                }
            }
        }
    }
}
